# Generated by Django 3.0.7 on 2020-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_desc', models.TextField()),
                ('service_img', models.FileField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
