# Generated by Django 3.0.7 on 2020-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.FileField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Background Images',
            },
        ),
        migrations.CreateModel(
            name='HepepsTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('other_names', models.CharField(blank=True, max_length=200, null=True)),
                ('img_url', models.FileField(upload_to='pics')),
                ('Bio', models.TextField()),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Hepeps Team',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_desc', models.TextField()),
                ('service_img', models.FileField(upload_to='pics')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
